### ISSUE TITLE
Bundler has no data, even after requesting an update

### ISSUE THREAD

**Issue by indirect** [ossert/ossert-web#16]
This is very neat! Sadly, the page for the Bundler project (https://ossert.evilmartians.io/bundler) has no data, and despite the lack of data, Ossert confidently declares that Bundler has an overall grade of "E". Pushing the "request update" button does not change anything or cause any data to appear.

**Comment by sclinede** [comment]
Woops! I'll check it manually and share the results) Thanks for pointing it out

**Comment by sclinede** [comment]
Okay. I found that data is cleaned before the data fetching process and if (and looks like that happened) data fetching process failed - all stored data will be absent.
So:
 - I fetched data for Bundler again and now it works well 
 - I prefer to remain this Issue to fix the problem in future

Thanks for your response!

**Comment by indirect** [comment]
thank you for the quick response!
